---
title: "Publications"
description-meta: "Information, pdfs, and coverage of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: custom.css
---

https://www.semanticscholar.org/paper/Object-detection-in-financial-reporting-documents-Sokerin-Volkova/dbd88e498eb5b81f466e86f0bc46ad8554a0a277

## Selected Work

### Applied and theory

Kushnarev, K., Sokerin, P., & Volkova, A. (2021). [Object detection in financial reporting documents for subsequent recognition](https://www.semanticscholar.org/paper/Object-detection-in-financial-reporting-documents-Sokerin-Volkova/dbd88e498eb5b81f466e86f0bc46ad8554a0a277). *International Journal of Advanced Smart Convergence*, *10*, 1–11 (in Eng.). \[[pdf](https://koreascience.kr/article/JAKO202112362357473.pdf)\]

<details>
<summary><strong>Abstract</strong></summary>
Document page segmentation is an important step in building a quality optical character recognition module. The study examined already existing work on the topic of page segmentation and focused on the development of a segmentation model that has greater functional significance for application in an organisation, as well as broad capabilities for managing the quality of the model. The main problems of document segmentation were highlighted, which include a complex background of intersecting objects. As classes for detection, not only classic text, tables and figures were selected, but also additional types, such as signatures, logos and tables without borders (or with partially missing borders). This made it possible to pose a non-trivial task of detecting nonstandard document elements. The authors compared existing neural network architectures for object detection based on published research data. The most suitable architecture was RetinaNet. To ensure the possibility of quality control of the model, a method based on neural network modelling using the RetinaNet architecture is proposed. During the study, several models were built, the quality of which was assessed on the test sample using the mean average precision metric. The best result among the constructed algorithms was shown by a model that includes four neural networks: the focus of the first neural network is on detecting tables and tables without borders, the second – seals and signatures, the third – pictures and logos, and the fourth – text. As a result of the analysis, it was revealed that the approach based on four neural networks showed the best results in accordance with the objectives of the study on the test sample in the context of most classes of detection. The method proposed in the article can be used to recognise other objects. A promising direction in which the analysis can be continued is the segmentation of tables; the areas of the table that differ in function will act as classes: heading, cell with a name, cell with data, and empty cell. 
</details>

### Political business-cycles

Kushnarev, K. (2020). [Transformation of Kuznets cycles in post-socialist countries. Relationship of the cycles with economic growth](https://cyberleninka-ru.translate.goog/article/n/transformatsiya-tsiklov-kuznetsa-v-postsotsialisticheskih-stranah-svyaz-issleduemyh-tsiklov-s-ekonomicheskim-rostom?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp). *Scientific Works of the Free Economic Society of Russia*, *224*, 541–553 (in Rus.). \[[pdf](https://www.dropbox.com/scl/fi/oal5v6v8y2gga16zb11w6/transformatsiya-tsiklov-kuznetsa-v-postsotsialisticheskih-stranah-svyaz-issleduemyh-tsiklov-s-ekonomicheskim-rostom.pdf?rlkey=njgpiddtty4wef67qngt9isgb&dl=0)\]

**Awarded a prize in the Free Economic Society [competition](https://www-veorus-ru.translate.goog/%d0%b4%d0%b5%d1%8f%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d0%be%d1%81%d1%82%d1%8c/mezhdunarodnyy-konkurs-nauchnykh-rabot-molodezhi/?_x_tr_sl=mk&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp)**

<details>
<summary><strong>Abstract</strong></summary>
The paper clarifies the concept of Kuznets cycles, dividing it into three rhetorics: economic, political, and environmental. The author highlights the synthesis of economic and political rhetoric within the framework of institutional theory. Building on this tradition, the author empirically demonstrates the transformations of Kuznets cycles from 1905 to 2016 in a step-by-step manner. The article proposes a theoretical model of the Kuznets cycle in post-socialist countries, which could serve as a starting point for forecasting medium-term cycles in the post-Soviet space.
</details>

<center><hr style="width:50%"></center>

Kushnarev, K., & Bolvachev, A. (2020). [Economic views of S. Kuznets and the reception of the theory of medium-term cycles in the political economy narrative](https://cyberleninka-ru.translate.goog/article/n/ekonomicheskie-vzglyady-s-kuznetsa-i-retseptsiya-teorii-srednesrochnyh-tsiklov-v-politekonomicheskom-narrative?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp). *University Bulletin*, *8*, 88–101 (in Rus.). \[[pdf](https://www.dropbox.com/scl/fi/rd17evhf1n0y9wks9s4ai/ekonomicheskie-vzglyady-s-kuznetsa-i-retseptsiya-teorii-srednesrochnyh-tsiklov-v-politekonomicheskom-narrative.pdf?rlkey=1z8irnz8jlwnd2nelw7o9lk8c&dl=0)\]

<details>
<summary><strong>Abstract</strong></summary>
This paper explores the key ideas of Nobel laureate Simon Kuznets’ economic thought through the lens of four micro-case studies. It analyzes the major works of Kuznets and his advisor, Wesley C. Mitchell, and traces the influence of Kuznets’ methodological approach on the development of economic theory. The paper also examines how the mechanics of Kuznets’ research are received in modern political economy, particularly in the works of Daron Acemoglu and James Robinson. The appendix includes a brief analysis of the political interpretation of Kuznets’ cycle theory as proposed by Acemoglu and Robinson. Overall, the article synthesizes previous research on Kuznets’ economic views and highlights the relevance of his experiential approach for contemporary analysis.
</details>

### Art-market

Kushnarev, K., et al. (2020). [The mechanism of self-regulation of the art market as a factor of counteraction to the legalization of financial flows](https://cyberleninka-ru.translate.goog/article/n/mehanizm-samoregulirovaniya-art-rynka-kak-faktor-protivodeystviya-legalizatsii-finansovyh-potokov?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp). *Financial Research*, *4*, 94–108 (in Rus.). \[[pdf](https://www.dropbox.com/scl/fi/hqlzee77e73vztp8s0bol/mehanizm-samoregulirovaniya-art-rynka-kak-faktor-protivodeystviya-legalizatsii-finansovyh-potokov.pdf?rlkey=bmvk26ahvkr06m7fks1koozwu&dl=0)\]

<details>
<summary><strong>Abstract</strong></summary>
Purpose. The aim of this article is to analyze the main mechanisms for countering money laundering in the art market across four economic regions: the United States, the European Union, South Africa, and Russia.

Structure/Methodology/Approach. The article consists of five sections, focusing on an analysis of the current state of the art market and the development of a model to combat money laundering within it. The authors adopt a general economic approach to the study, while also emphasizing the importance of institutional methodology for analyzing the process in question.

Findings. The article provides an assessment of the current state of anti-money laundering efforts in Russia’s art market. It highlights a lack of academic research on the mechanisms of money laundering in this sector and, consequently, an insufficient understanding of the policies aimed at combating it. The authors present their own perspective on the future development of anti-money laundering measures in the Russian art market.

Originality/Value. The institutional model of regulation proposed for the art market can serve as a foundation for developing a regulatory framework based on the principle of self-regulation. This approach could help avoid excessive regulatory pressure on market participants. The authors argue that the development of a national strategy to counter money laundering in emerging markets—particularly in the art market—must be brought to the forefront of policy discussions without delay.
</details>

<center><hr style="width:50%"></center>

Kushnarev, K., & Bolvachev, A. (2020). [Mathematical and statistical model of price formation in the art market: finance and market equilibrium](https://www.finance-man.ru/index.php/journal/article/view/264). *Financial Management*, *1*, 51–63 (in Rus.). \[[pdf](https://www.finance-man.ru/index.php/journal/article/view/264)\]

<details>
<summary><strong>Abstract</strong></summary>
The article examines the specific features of price formation for art objects. The authors highlight the ambiguity of approaches to valuing works of art and the unique mechanisms and institutions of the art market. A mathematical and statistical model is proposed, explaining price formation as a result of the equilibrium between supply and demand. The article argues that the art market remains under-researched in Russian-language academic discourse. At the same time, it introduces an approach to studying the art market that has not previously been applied in Russian-language papers. The role and nature of finance in shaping art prices are also analyzed. This article may be of interest to auction houses as key institutions of the art market, as well as to both theoretical and applied economists and anyone interested in art.
</details>

### Social Psychology

Kushnarev, K., & Smirnova, Ya. (2018). [Theoretical and methodological foundations of research of interpersonal attraction](https://bppasu-ru.translate.goog/article/view/4231?_x_tr_sch=http&_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp). *Bulletin of Psychology and Pedagogy of Altai State University*, *2*, 89–108 (in Rus.). \[[pdf](https://www.dropbox.com/scl/fi/rrs055tl1teg5tiwe3t6p/4231-13963-1-10-20180627.pdf?rlkey=r2dffwxsmklfhet83nqsln6xo&dl=0)\]

<details>
<summary><strong>Abstract</strong></summary>
The article reviews and systematizes the main approaches to studying interpersonal attraction. It analyzes the classical paradigm of interpersonal attraction developed by D. Byrne and the non-classical concept proposed by R. Montoya. A two-factor model of interpersonal attraction is presented for readers' consideration. The article also provides a list of promising research methods for studying attractiveness, aimed at scholars working in this field. This article may be of interest to anyone exploring the dynamics of interpersonal attractiveness.
</details>

<center><hr style="width:50%"></center>

Kushnarev, K., & Smirnova, Ya. (2017). [Motivations for refusing assistance in adolescents in the context of the phenomenon of interpersonal attraction](https://bppasu-ru.translate.goog/article/view/3290?_x_tr_sch=http&_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp). *Bulletin of Psychology and Pedagogy of Altai State University*, *3*, 62–74 (in Rus.). \[[pdf](https://www.dropbox.com/scl/fi/ak9dz7tf81afxfk0qy9o1/3290-10404-1-10-20170930.pdf?rlkey=io30vic0foh50dy6186wtravg&dl=0)\]

**This paper received a commendation from the [American Psychological Association](https://en.wikipedia.org/wiki/American_Psychological_Association) and the [Moscow Psychological Society](https://ru-m-wikipedia-org.translate.goog/wiki/%D0%9C%D0%BE%D1%81%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%BE%D0%B5_%D0%BF%D1%81%D0%B8%D1%85%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D0%BE%D0%B1%D1%89%D0%B5%D1%81%D1%82%D0%B2%D0%BE?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp) in the [Step into the Future](https://www-step--into--the--future-ru.translate.goog/?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp) competition**

<details>
<summary><strong>Abstract</strong></summary>
The article is devoted to one of the components of prosocial motivation—namely, the motivation to avoid helping others. It examines the role of this avoidance motivation among adolescents, particularly in the context of the risk of damaging social relationships with peers. The article also explores the role of interpersonal attraction in shaping prosocial behavior in adolescents.
</details>

<center><hr style="width:50%"></center>

Full list of published papers and conference proceedings is [here](https://scholar.google.com/citations?user=hNCef-4AAAAJ&hl=ru&oi=ao). Research statement is [here](https://kkushnarev.github.io/projects.html).
