---
title: "Working Papers"
description-meta: "Information, pdfs, and coverage of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: custom.css
---

## Working Papers

Kushnarev, K. (2024). Labour market concentration since the British Industrial Revolution. *Working Paper*. \[[pdf](/files/WP2.pdf)\] \[[slides](https://www.dropbox.com/scl/fi/7bay01qimaelbr0nbff13/Presentation__WP-12.pdf?rlkey=9bqm8tmp7cxf1nahw9e6t3lgb&st=3pw3ldbn&dl=0)\] 

**Covered by [Economic Statistics Centre of Excellence](https://www.escoe.ac.uk/labour-market-concentration-since-the-british-industrial-revolution/)**

<details>
<summary><strong>Abstract</strong></summary>
This paper highlights an economic history perspective on labour share dynamics during the second phase of the British Industrial Revolution. It addresses two broad questions: 1) Did market concentration increase between 1851 and 1911? 2) If so, did the labour share decline, as suggested by ongoing debates? I use census data from 1851 to 1911 to answer these questions, focusing on local labour markets. Employing different specifications of market concentration, I found a surprising doubling in market concentration during this period, as measured by both the Herfindahl-Hirschman Index and Concentration Ratio approaches. However, local labour market concentration decreased as the labour market expanded. I further explore this by providing a counterfactual analysis, showing that a one standard deviation increase in creative destruction leads to a 50% rise in new entrants. Consequently, I offer two explanations for the presented results. The first is that local labour market concentration is more suitable for analysing labour share, making it a more practical and data-driven approach. The second explanation is that the decline and rise of labour share trigger uneven growth through redistribution and creative destruction. This explanation is more theoretical but still supports my results. In the future, a greater focus on the first stage of the British Industrial Revolution could lead to the developing of a more grounded theory.
</details>

<center><hr style="width:50%"></center>

Kushnarev, K. (2024). Spillover effects from chess, 1891–2021. *Working Paper*. \[[pdf](https://scholar.google.com/)\]

<details>
<summary><strong>Abstract</strong></summary>
This paper explores the formation of upper-tail human capital under socialism and its longstanding impact on economic and political participation. Based on this motivation, I have developed a model of the interplay between economic and intellectual life, where intellectual competition in chess explains the variation of economic and political participation once it becomes available. I have collected a novel dataset of \textit{2 155 chess protocols and 11 115 unique names} of chess players between 1891 and 2021 in the three levels of tournaments: local (cities and towns), republics, and international competitions held in the USSR and, after 1991, in Russia. Based on the data, I have found a variation in chess competitiveness by the level of tournaments and geographical units. It accounts for a more than 6 times decrease in the local competitiveness in the 30-s and, more importantly, in the 70-s and 80-s. Furthermore, this variation allows me to frame future opportunities to explore causal relationships between chess competitiveness and a) the probability of city participation in the cooperative movement, introduced in 1989; b) the exposure of political protest activities in 2007-2017 at the level of the city.
</details>

<center><hr style="width:50%"></center>

On the future development of working papers in the [Research Statement](https://kkushnarev.github.io/projects.html).
